version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home

  webapp:
    build: ./webapp  # Update this path to the actual location of your Flask Dockerfile
    container_name: webapp
    ports:
      - "80:5000"  # This forwards the host's port 80 to the container's port 5000
    volumes:
      - ./webapp:/app  # Update this path if necessary

  git:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3000:3000"  # Gitea web interface
      - "2222:22"    # SSH access to repositories
    volumes:
      - ./gitea:/data

volumes:
  jenkins_data:
    driver: local
